### PR TITLE
Themes and playing media icon. issue #38

### PR DESCRIPTION
**Pull request by shapkarin**
- Themes option
- Dark theme
- Icon to show if tab is playing media
- Move input to left and make it larger 
  - leave place for list edit icon, hope that later it will be implemented
- Add logo and some info to the README
- Update dependencies

#38

### CODE REVIEW

**Comment by nsand** [comment]
Thanks for all the hard work on this, @shapkarin . I should have some time to look at the PR over the weekend.

**Comment by shapkarin** [comment]
@nsand OK, feel free to share yours thoughts

**Comment by shapkarin** [comment]
ping

**Comment by nsand** [comment]
Hey, @shapkarin Sorry work has been crazy lately and some RL things have popped up on top of that. I'll try reviewing this soon.

**Comment by shapkarin** [comment]
Got that. Thanks for the answer. Maybe I will add tests to this repo later.

**Comment by shapkarin** [comment]
@nsand Hi, I recently found that with a real big list styled-components performs slower than previous tab-glutton version. I think I need to add this optimization https://github.com/nsand/tab-glutton/issues/39 to the current PR.

**Comment by nsand** [comment]
Thanks for considering perf in this! I’ll have some time this weekend to take a look.

**Comment by nsand** [comment]
Hey, @shapkarin. I started looking at the changes and things are looking good so far. I haven't worked with styled-components yet, so I'm going to brush up on them a bit before continuing on. But just wanted to thank you for your patience while I review this.

**Comment by shapkarin** [comment]
It looks like it's just a higher-order component. But I still think that we need to add something like `react-window` to produce the next stable release.

**Comment by shapkarin** [comment]
I will try to make find time for that too.. and fell free to help me with #39

**Comment by shapkarin** [comment]
Hello @nsand can you please recheck this PR and approve with my changes extension still has enough performance for the new release. For the next one release I will find time to close the #39 with a new PR.

**Comment by shapkarin** [comment]
Hello. It's about half of year I use my fork and don't get any problems with performance. I guess that my PR is fine.
Please have a look.

**Comment by nsand** [comment]
> Hello. It's about half of year I use my fork and don't get any problems with performance. I guess that my PR is fine.
> Please have a look.

Thanks @shapkarin . I'm so sorry for this taking so long to get merged in. I appreciate your persistence and contribution! I hope you're doing well and staying healthy.

**Comment by shapkarin** [comment]
thanks

**Pull request merged**
